using System;
using System.IO;
using System.Text;
class P { static void Main() {
  var b = new StringBuilder();
  b.AppendLine("import 'package:isar/isar.dart';");
  b.AppendLine("");
  b.AppendLine("part 'culte.g.dart';");
  b.AppendLine("");
  b.AppendLine("@collection");
  b.AppendLine("class Culte {");
  b.AppendLine("  Id isarId = Isar.autoIncrement;");
  b.AppendLine("");
  b.AppendLine("  @Index(unique: true, replace: true)");
  b.AppendLine("  late String id;");
  b.AppendLine("");
  b.AppendLine("  late DateTime dateCulte;");
  b.AppendLine("  String? titre;");
  b.AppendLine("  double montantCotisation = 50.0;");
  b.AppendLine("  String? notes;");
  b.AppendLine("  DateTime? updatedAt;");
  b.AppendLine("  DateTime createdAt = DateTime.now();");
  b.AppendLine("  int version = 1;");
  b.AppendLine("  String deviceId = '';");
  b.AppendLine("  bool isDeleted = false;");
  b.AppendLine("  DateTime? deletedAt;");
  b.AppendLine("  String? deletedBy;");
  b.AppendLine("");
  b.AppendLine("  /// IDs des membres actifs au moment de la création du culte.");
  b.AppendLine("  /// Les membres ajoutés après cette date n'apparaîtront pas dans l'UI du culte.");
  b.AppendLine("  /// Liste vide signifie ancien culte (avant cette correction) :");
  b.AppendLine("  /// l'UI utilise alors le fallback sur les cotisations.");
  b.AppendLine("  @Index()");
  b.AppendLine("  List<String> memberIds = [];");
  b.AppendLine("");
  b.AppendLine("  @ignore");
  b.AppendLine("  String get dateFormatee {");
  b.AppendLine("    const mois = ['Janvier','Février','Mars','Avril','Mai','Juin',");
  b.AppendLine("                   'Juillet','Août','Septembre','Octobre','Novembre','Décembre'];");
  b.AppendLine("    final wd = dateCulte.weekday;");
  b.AppendLine("    final nomJour = wd == 7 ? 'Dimanche' : ['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'][wd-1];");
  b.Append("    return '").Append("$nomJour ${dateCulte.day} ${mois[dateCulte.month - 1]} ${dateCulte.year}"); b.AppendLine("';");
  b.AppendLine("  }");
  b.AppendLine("");
  b.AppendLine("  // Helper for JSON (InsForge)");
  b.AppendLine("  Map<String, dynamic> toJson() => {");
  b.AppendLine("    'date_culte': dateCulte.toIso8601String().substring(0, 10),");
  b.AppendLine("    if (titre != null) 'titre': titre,");
  b.AppendLine("    'montant_cotisation': montantCotisation,");
  b.AppendLine("    if (notes != null) 'notes': notes,");
  b.AppendLine("    if (updatedAt != null) 'updated_at': updatedAt!.toIso8601String(),");
  b.AppendLine("    'created_at': createdAt.toIso8601String(),");
  b.AppendLine("    'version': version,");
  b.AppendLine("    'device_id': deviceId,");
  b.AppendLine("    'is_deleted': isDeleted,");
  b.AppendLine("    if (deletedAt != null) 'deleted_at': deletedAt!.toIso8601String(),");
  b.AppendLine("    if (deletedBy != null) 'deleted_by': deletedBy,");
  b.AppendLine("    'member_ids': memberIds,");
  b.AppendLine("  };");
  b.AppendLine("");
  b.AppendLine("  static Culte fromJson(Map<String, dynamic> json) {");
  b.AppendLine("    return Culte()");
  b.AppendLine("      ..id = json['id'] as String");
  b.AppendLine("      ..dateCulte = DateTime.parse(json['date_culte'] as String)");
  b.AppendLine("      ..titre = json['titre'] as String?");
  b.AppendLine("      ..montantCotisation = (json['montant_cotisation'] as num?)?.toDouble() ?? 50.0");
  b.AppendLine("      ..notes = json['notes'] as String?");
  b.AppendLine("      ..updatedAt = json['updated_at'] == null");
  b.AppendLine("          ? null");
  b.AppendLine("          : DateTime.parse(json['updated_at'] as String)");
  b.AppendLine("      ..createdAt = json['created_at'] == null");
  b.AppendLine("          ? DateTime.now()");
  b.AppendLine("          : DateTime.parse(json['created_at'] as String)");
  b.AppendLine("      ..version = (json['version'] as num?)?.toInt() ?? 1");
  b.AppendLine("      ..deviceId = json['device_id'] as String? ?? ''");
  b.AppendLine("      ..isDeleted = json['is_deleted'] as bool? ?? false");
  b.AppendLine("      ..deletedAt = json['deleted_at'] == null");
  b.AppendLine("          ? null");
  b.AppendLine("          : DateTime.parse(json['deleted_at'] as String)");
  b.AppendLine("      ..deletedBy = json['deleted_by'] as String?");
  b.AppendLine("      ..memberIds = (json['member_ids'] as List<dynamic>?)");
  b.AppendLine("          ?.map((e) => e as String)");
  b.AppendLine("          .toList() ?? [];");
  b.AppendLine("  }");
  b.AppendLine("}");
  File.WriteAllText(Path.Combine(Directory.GetCurrentDirectory(), "cotis_app/lib/models/culte.dart"), b.ToString(), new UTF8Encoding(false));
  Console.WriteLine("done");
}}
